# Generated by Django 3.2.9 on 2022-02-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20211212_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='equipment_mode',
            field=models.CharField(choices=[('AP', 'аварийный ремонт'), ('TP', 'текущий ремонт'), ('XP', 'холодный резерв'), ('on', 'в работе')], default='on', max_length=3),
        ),
    ]
